services:
  app:
    image: xoderockson/xode-core-ondemand:latest
    container_name: xode-core-ondemand
    env_file:
      - .env
    ports:
      - 3045:3000
    volumes:
      - /var/www/xode/xode-core-ondemand/.env:/usr/src/app/.env
